name: Release

defaults:
  run:
    shell: bash -le {0}

concurrency:
  group: ${{ github.event.inputs.ref || github.ref }}-workflow-release
  cancel-in-progress: true

on:
  push:
  release:
    types: [ published ]
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, Tag or Commit SHA'
        required: false
        default: ''
      pr_number:
        description: 'PR Number'
        required: false
        type: number
      upload_pypi:
        description: 'Upload to PyPI'
        type: boolean
        required: false
        default: false
      upload_release:
        description: 'Upload to release (it only works with a tag ref)'
        type: boolean
        required: false
        default: false

env:
  RELEASE_MODE: 1
  CI: 1
  MAX_JOBS: 4
  ref: ${{ github.event.inputs.ref || github.ref }}

jobs:
  release-source:
    runs-on: ubuntu-latest
    if: (github.event_name == 'release' || github.event.inputs.upload_pypi == 'true') && !cancelled()

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ env.ref }}

      - uses: actions/setup-python@v6
        with:
          python-version: 3.14
          cache: 'pip'

      - name: Install requirements
        run: pip install pip build setuptools twine packaging -U

      - name: Build package
        run: |
          python -m build --sdist
          twine check dist/*

      - name: Upload sdist to pypi
        if: (github.event_name == 'release' || github.event.inputs.upload_pypi == 'true') && !cancelled()
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_KEY }}
        run: |
          python -m twine upload dist/*gz
